version: 1
runners:
  Machine:
    config-id: 2
images:
  image:
    image: node:20
    auth:
      username: santhosh270
      password: Catalyst@test123
jobs:
  Deploy_Client_Functions:
    runner: Machine
    image: image
    steps:
      - npm i -g netlify-cli
      - netlify --version
      - npm install
      - npm run build
      - netlify deploy --auth nfp_wwCvhjaRtWtrbnHgtenXadyHfmsWMpEBef3a --site 227f2a11-d754-4f35-82e0-62f167ed337c
stages:
  - name: test
    jobs: 
      - Deploy_Client_Functions
variables:
  VercelToken: DWkAIYRcGfsaZqkJmK2LtD3u