version: 1
runners:
  Machine:
    config-id: 2
images:
  image:
    image: node:20
    auth:
      username: santhosh270
      password: Catalyst@test123
jobs:
  Deploy_Client_Functions:
    runner: Machine
    image: image
    steps:
      - npm i netlify-cli
      - netlify --version
      - netlify deploy --auth nfp_iP3ca4jZdDgFwiQKGeetKuHto5LDFFgTb0c8
stages:
  - name: test
    jobs:
      - Deploy_Client_Functions
variables:
  VercelToken: DWkAIYRcGfsaZqkJmK2LtD3u