version: 1
runners:
  Machine:
    config-id: 2
images:
  image:
    image: node:20
    auth:
      username: santhosh270
      password: Catalyst@test123
jobs:
  Deploy_Client_Functions:
    runner: Machine
    image: image
    steps:
      - npm i -g netlify-cli
      - netlify --version
      - netlify build
      - netlify deploy --auth nfp_iP3ca4jZdDgFwiQKGeetKuHto5LDFFgTb0c8 --site 448d391a-4df3-43f8-ab7b-c93e5127851f
stages:
  - name: test
    jobs:
      - Deploy_Client_Functions
variables:
  VercelToken: DWkAIYRcGfsaZqkJmK2LtD3u