version: 1
runners:
  Machine:
    config-id: 2
images:
  image:
    image: node:20
    auth:
      username: << env.USER_NAME >>
      password: << env.PASSWORD >>
jobs:
  Deploy_Client_Functions:
    runner: Machine
    image: image
    steps:
      - npm i -g netlify-cli
      - netlify --version
      - npm install
      - npm run build
  Deployment_Approval:
    type: approval
    specification:
      reviewers:
        - santhosh.mahendiran@zohocorp.com
      message: |-
        Hi,

        Kindly approve the latest build.
      steps:
        - npm run build
        - netlify deploy --auth << env.NETLIFY_TOKEN >> --site << env.SITE_ID >>
stages:
  - name: build
    jobs:
      - Deploy_Client_Functions
  - name: deploy
    jobs:
      - Deployment_Approval