version: 1
runners:
  Machine:
    config-id: 2
images:
  image:
    image: node:20
    auth:
      username: << env.USER_NAME >>
      password: << env.PASSWORD >>
jobs:
  Deploy_Client_Functions:
    runner: Machine
    image: image
    steps:
      - npm i -g netlify-cli
      - netlify --version
  Deployment_Approval:
    type: approval
    specification:
      reviewers:
        - santhosh.mahendiran@zohocorp.com
      message: |-
        Hi,

        Kindly approve the latest build.
  Deployment:
    runner: Machine
    image: image
    steps:
      - npm i -g netlify-cli
      - netlify --version
      - npm install  
      - npm run build
      - netlify deploy --auth << env.NETLIFY_TOKEN >> --site << env.SITE_ID >>
  test_build:
    artifacts:
      upload:
        - type: zip
          regex:
            - /catalyst/**
          name: build
          location: stratus://netlify-builds/
    runner: Machine
    image: image
    cwd: /catalyst/
    steps:
      - echo `ls`
      - echo `pwd`
      - echo `cd catalyst && ls`
stages:
  - name: build
    jobs:
      - Deploy_Client_Functions
  - name: deploy
    jobs:
      - Deployment_Approval
  - name: Deployment
    jobs:
      - Deployment
  - name: test_build
    jobs:
      - test_build